const GET_MEASUREMENTS = "GET_MEASUREMENTS";
const ADD_MEASUREMENT = "ADD_MEASUREMENT";
const EDIT_MEASUREMENT = "EDIT_MEASUREMENT";
const DELETE_MEASUREMENT = "DELETE_MEASUREMENT";
const LOADING_MEASUREMENTS = "LOADING_MEASUREMENTS";
const ERROR_MEASUREMENTS = "ERROR_MEASUREMENTS";

export {
  GET_MEASUREMENTS,
  ADD_MEASUREMENT,
  EDIT_MEASUREMENT,
  DELETE_MEASUREMENT,
  LOADING_MEASUREMENTS,
  ERROR_MEASUREMENTS,
};
