const CREATE_USER = "CREATE_USER";
const LOGIN_USER = "LOGIN_USER";
const LOGOUT_USER = "LOGOUT_USER";
const GET_USER = "GET_USER";
const LOADING_USER = "LOADING_USER";
const ERROR_USER = "ERROR_USER";

export {
  CREATE_USER,
  LOGIN_USER,
  LOGOUT_USER,
  GET_USER,
  LOADING_USER,
  ERROR_USER,
};
