const GET_CLIENTS = "GET_CLIENTS";
const ADD_CLIENT = "ADD_CLIENT";
const EDIT_CLIENT = "EDIT_CLIENT";
const DELETE_CLIENT = "DELETE_CLIENT";
const LOADING_CLIENTS = "LOADING_CLIENTS";
const ERROR_CLIENTS = "ERROR_CLIENTS";

export {
  GET_CLIENTS,
  ADD_CLIENT,
  EDIT_CLIENT,
  DELETE_CLIENT,
  LOADING_CLIENTS,
  ERROR_CLIENTS,
};
